name: Update GEE Catalog

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger
  
jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas crawl4ai
        
    - name: Download and check for changes
      run: |
        # Run the download script
        python download_gee_catalog.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add docs/
        git add download_progress_datasets_catalog.json
        
        # Try to commit and push changes. Don't fail if there are no changes.
        git commit -m "Update GEE catalog documentation" || exit 0
        git push 